version: '3.3'

services:
  postgres:
    image: postgres:13
    container_name: js-postgres
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    network_mode: "host"

volumes:
  postgresqldata: